### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Brandon-Isaac** [skills/write-javascript-actions#42] opened 2024-05-22 09:04 UTC
### The new cloned repository seems not to be working
I have cloned the repo and refreshed the page several times but the repo is not updating and the readME file remains the same

### I have done the steps below

1. Go to github skills
2. Click on javascript actions
3. Scroll down to Start course
4. Enter your new repository name
5. Click create repository
6. Refresh the repository
7. See error ,no New ReadME file as stated in the read me

Please include screenshots.

**Comment by hectorsector** [comment] 2024-05-22 20:25
Duplicate of https://github.com/skills/write-javascript-actions/issues/37

**Closed by hectorsector** 2024-05-22 20:25 UTC
Labels: bug
